# nbload2.inc - contains common code for stage 1 / 1.5 that gets stashed in sector 2
# Copyright 2022 The NexNix Project
#
# Licensed under the Apache License, Version 2.0 (the "License")#
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Welcome banner
welcomeBanner2:
.asciz "\r\nCopyright (C) 2021 - 2022 The NexNix Project. All rights reserved.\r\n"
